### ISSUE TITLE
Trajectory file cannot be written with UFCalculator

### ISSUE THREAD

**Issue by sunghjung3** [uf3/uf3#46]
This mini-script demonstrates the issue. I have an ASE Atoms object and want to run dynamics/optimization with it using the UFCalculator from UF3.

```
from uf3.forcefield import calculator
from ase import Atoms
from ase.io import trajectory
from ase.optimize.sciopt import SciPyFminCG

atoms = Atoms(...)
uf3_calc = calculator.UFCalculator(uf3_model)
atoms.calc = uf3_calc
traj = trajectory.Trajectory(traj_file, mode='w', atoms=atoms)
dyn = SciPyFminCG(atoms)
dyn.attach(traj.write)
dyn.run(steps=1)
```

The last line above raises an attribute error:

```
Traceback (most recent call last):
  File "/home/sung/UFMin/sung/data/pt_bulk/ufmin.py", line 74, in <module>
    dyn.run(steps=1, fmax=ufmin_fmax)
  File "/home/sung/miniforge3/envs/ufmin/lib/python3.10/site-packages/ase/optimize/sciopt.py", line 113, in run
    self.callback(None)
  File "/home/sung/miniforge3/envs/ufmin/lib/python3.10/site-packages/ase/optimize/sciopt.py", line 102, in callback
    self.call_observers()
  File "/home/sung/miniforge3/envs/ufmin/lib/python3.10/site-packages/ase/optimize/optimize.py", line 108, in call_observers
    function(*args, **kwargs)
  File "/home/sung/miniforge3/envs/ufmin/lib/python3.10/site-packages/ase/io/trajectory.py", line 132, in write
    self._write_atoms(image, **kwargs)
  File "/home/sung/miniforge3/envs/ufmin/lib/python3.10/site-packages/ase/io/trajectory.py", line 167, in _write_atoms
    c.write(name=calc.name)
AttributeError: 'UFCalculator' object has no attribute 'name'
```

If I try to work around this by setting `calc.name` manually in my mini-script, it raises yet another attribute error:

```
Traceback (most recent call last):
  File "/home/sung/UFMin/sung/data/pt_bulk/ufmin.py", line 75, in <module>
    dyn.run(steps=1, fmax=ufmin_fmax)
  File "/home/sung/miniforge3/envs/ufmin/lib/python3.10/site-packages/ase/optimize/sciopt.py", line 113, in run
    self.callback(None)
  File "/home/sung/miniforge3/envs/ufmin/lib/python3.10/site-packages/ase/optimize/sciopt.py", line 102, in callback
    self.call_observers()
  File "/home/sung/miniforge3/envs/ufmin/lib/python3.10/site-packages/ase/optimize/optimize.py", line 108, in call_observers
    function(*args, **kwargs)
  File "/home/sung/miniforge3/envs/ufmin/lib/python3.10/site-packages/ase/io/trajectory.py", line 132, in write
    self._write_atoms(image, **kwargs)
  File "/home/sung/miniforge3/envs/ufmin/lib/python3.10/site-packages/ase/io/trajectory.py", line 169, in _write_atoms
    c.write(parameters=calc.todict())
  File "/home/sung/miniforge3/envs/ufmin/lib/python3.10/site-packages/ase/calculators/calculator.py", line 623, in todict
    for key, value in self.parameters.items():
AttributeError: 'UFCalculator' object has no attribute 'parameters'
```

I think the incorporation of UF3 into ASE should be made more complete.

**Comment by sunghjung3** [comment]
Closing, since it was resolved in #110
